### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by nies14** [zczcwh/PoseFormer#16]
Trying to run the pre-trained model & training new models...Getting bellow error

RuntimeError: CUDA out of memory. Tried to allocate 366.00 MiB (GPU 0; 7.79 GiB total capacity; 4.50 GiB already allocated; 303.38 MiB free; 4.62 GiB reserved in total by PyTorch)

Reducing batch size also doesn't work

Processor: Core i9
Ram: 64 GB
GPU: RTX 3070

The Traceback: '
Traceback (most recent call last):
  File "run_poseformer.py", line 309, in <module>
    predicted_3d_pos = model_pos_train(inputs_2d)
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/Desktop/Research/PoseFormer-main/common/model_poseformer.py", line 178, in forward
    x = self.Spatial_forward_features(x)
  File "/home/user/Desktop/Research/PoseFormer-main/common/model_poseformer.py", line 154, in Spatial_forward_features
    x = blk(x)
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/Desktop/Research/PoseFormer-main/common/model_poseformer.py", line 81, in forward
    x = x + self.drop_path(self.attn(self.norm1(x)))
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/Desktop/Research/PoseFormer-main/common/model_poseformer.py", line 56, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 366.00 MiB (GPU 0; 7.79 GiB total capacity; 4.50 GiB already allocated; 303.38 MiB free; 4.62 GiB reserved in total by PyTorch)
'

**Comment by nies14** [comment]
Had to use the below line to solve this
os.environ['CUDA_VISIBLE_DEVICES'] = '1, 2, 3,4'
