### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype' of Wild video

### ISSUE THREAD

**Issue by Whisht** [zczcwh/PoseFormer#27]
I follow the instruction 
* (https://github.com/facebookresearch/VideoPose3D/blob/main/INFERENCE.md) and 
* (https://colab.research.google.com/github/kuboyoo/VideoPose3D/blob/master/VideoPose3D.ipynb) .

With the same pre-processed video as well as same hyperparameters, `VideoPose3D` runs normally, but `PoseFormer` has this bug:
```
Traceback (most recent call last):
  File "/data/xielongfei/code/github/PoseFormer-main/run_poseformer.py", line 589, in <module>
    prediction = evaluate(gen, return_predictions=True)
  File "/data/xielongfei/code/github/PoseFormer-main/run_poseformer.py", line 511, in evaluate
    inputs_3d = torch.from_numpy(batch.astype('float32'))
AttributeError: 'NoneType' object has no attribute 'astype'.
```
It seems the dataloading procedure has some problem.

**Comment by FinallyKiKi** [comment]
I also have this qustion. 
BTW, I change the code somewhere and get this result:
![微信图片_20220325101205](https://user-images.githubusercontent.com/57625877/160040964-b57894e3-3586-4935-ae19-af505349c276.png)

**Comment by ClimberXIE** [comment]
I also have this question!
And I change the code but get bad results.
![image](https://user-images.githubusercontent.com/74538797/160797617-adf93061-0c08-4ea4-99d4-af68faec0c7b.png)

**Comment by AO2233** [comment]
@Whisht  @FinallyKiKi @ClimberXIE 
This Net input format is human3.6M's 17 points 
You need to change the COCO  format 17 points from the detectron2 of VideoPose3d to human3.6M's 17 points 
As for the code, click here for reference:
https://github.com/fabro66/GAST-Net-3DPoseEstimation/blob/master/tools/mpii_coco_h36m.py
and then
```python
# first load your videopose 2d coco points
loaded = np.load('PoseFormer/data/data_2d_custom_myvideos.npz', allow_pickle=True)
data = loaded['positions_2d'].item()
for i in data:
    # convert them to human3.6M format
    data[i]['custom'][0]=coco_h36m(data[i]['custom'][0])
np.savez_compressed('data_2d_custom_myvideos', positions_2d=data, metadata=loaded['metadata'])
```

**Comment by ClimberXIE** [comment]
Thank you for your reply !I have solved the problem now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zczcwh/PoseFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 中午12:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zczcwh/PoseFormer] AttributeError: 'NoneType' object has no attribute 'astype' of Wild video (Issue #27)





 
@Whisht  @FinallyKiKi @ClimberXIE
 This Net input format is human3.6M's 17 points
 You need to change the COCO  format 17 points from the detectron2 of VideoPose3d to human3.6M's 17 points
 As for the code, click here for reference:
 https://github.com/fabro66/GAST-Net-3DPoseEstimation/blob/master/tools/mpii_coco_h36m.py
 and then
 # first load your videopose 2d coco points loaded = np.load('PoseFormer/data/data_2d_custom_myvideos.npz', allow_pickle=True) data = loaded['positions_2d'].item() for i in data:     # convert them to human3.6M format     data[i]['custom'][0]=coco_h36m(data[i]['custom'][0]) np.savez_compressed('data_2d_custom_myvideos', positions_2d=data, metadata=loaded['metadata'])

**Comment by AO2233** [comment]
@ClimberXIE can you share your wild video inference result if you are free? **In my videos the results with gt81f.bin are not good as the example author gives.**
I want to know reason that is the input convert or the net weight caused it🤔

my email address is momiji _ao@outlook.com

Thank you!:)

**Comment by wshjtuk** [comment]
> Thank you for your reply !I have solved the problem now.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zczcwh/PoseFormer" ***@***.***&gt;; 发送时间:&nbsp;2022年3月31日(星期四) 中午12:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zczcwh/PoseFormer] AttributeError: 'NoneType' object has no attribute 'astype' of Wild video (Issue #27) @Whisht @FinallyKiKi @ClimberXIE This Net input format is human3.6M's 17 points You need to change the COCO format 17 points from the detectron2 of VideoPose3d to human3.6M's 17 points As for the code, click here for reference: https://github.com/fabro66/GAST-Net-3DPoseEstimation/blob/master/tools/mpii_coco_h36m.py and then # first load your videopose 2d coco points loaded = np.load('PoseFormer/data/data_2d_custom_myvideos.npz', allow_pickle=True) data = loaded['positions_2d'].item() for i in data: # convert them to human3.6M format data[i]['custom'][0]=coco_h36m(data[i]['custom'][0]) np.savez_compressed('data_2d_custom_myvideos', positions_2d=data, metadata=loaded['metadata']) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;



> Thank you for your reply !I have solved the problem now.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zczcwh/PoseFormer" ***@***.***&gt;; 发送时间:&nbsp;2022年3月31日(星期四) 中午12:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zczcwh/PoseFormer] AttributeError: 'NoneType' object has no attribute 'astype' of Wild video (Issue #27) @Whisht @FinallyKiKi @ClimberXIE This Net input format is human3.6M's 17 points You need to change the COCO format 17 points from the detectron2 of VideoPose3d to human3.6M's 17 points As for the code, click here for reference: https://github.com/fabro66/GAST-Net-3DPoseEstimation/blob/master/tools/mpii_coco_h36m.py and then # first load your videopose 2d coco points loaded = np.load('PoseFormer/data/data_2d_custom_myvideos.npz', allow_pickle=True) data = loaded['positions_2d'].item() for i in data: # convert them to human3.6M format data[i]['custom'][0]=coco_h36m(data[i]['custom'][0]) np.savez_compressed('data_2d_custom_myvideos', positions_2d=data, metadata=loaded['metadata']) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Hello,
I met the same problem but still fill to restore the bug by using coco_h36m transform. I use the script after Step4 in the VideoPose3D tutorial but still exist the same bug. Are there any other tricky bugs?
Thanks.

**Comment by wshjtuk** [comment]
> @ClimberXIE can you share your wild video inference result if you are free? **In my videos the results with gt81f.bin are not good as the example author gives.** I want to know reason that is the input convert or the net weight caused it🤔
> 
> my email address is [momiji_ao@outlook.com](mailto:momiji_ao@outlook.com)
> 
> Thank you!:)
> 
> update: (my result)
> 
> 1. the convert visualization
>    ![image](https://user-images.githubusercontent.com/59056753/161181493-8b2649bd-0a8a-4fc8-afd3-317a55aa1d2b.png)
> 2. video output
>    ![image](https://user-images.githubusercontent.com/59056753/161181925-d39bffb6-fe30-4b76-8e6c-60703e98d7e2.png)

Hello,
I met the same problem but still fill to restore the bug by using coco_h36m transform. I use the script after Step4 in the VideoPose3D tutorial but still exist the same bug. Are there any other tricky bugs?
I have also Emailed you, looking forward to your reply!
Thanks.

**Comment by AO2233** [comment]
@Whisht Yes, there is another problem with the code. Please refer to the email for details. You need to change the code somewhere.
This [code](https://github.com/zczcwh/PoseFormer/issues/27#issuecomment-1084048398) is for the problem of [FinallyKiKi](https://github.com/FinallyKiKi) and  [ClimberXIE](https://github.com/ClimberXIE).

**Comment by TomCatOnline** [comment]
> 
thanks for your solution
but can you specify where and what code exactly should i change to make the visualization run?
thanks again!

**Comment by TomCatOnline** [comment]
> @Whisht Yes, there is another problem with the code. Please refer to the email for details (In a nutshell, remove inputs_3d from the original code when you use it to visualizations). You need to change the code somewhere. This [code](https://github.com/zczcwh/PoseFormer/issues/27#issuecomment-1084048398) is for the problem of [FinallyKiKi](https://github.com/FinallyKiKi) and [ClimberXIE](https://github.com/ClimberXIE).

thanks for you solution
but can you specify where and what code exactly should i make changes to make visualizations run?
thanks again!

**Comment by safsin** [comment]
I'm trying to infer 3d human pose on custom videos using provided pretrained model (gt81f.bin). I've done the following preprocessing - 
1. Input 2d keypoints are in H3.6m format
2. Input 2d keypoints are normalized keeping width in the range [-1, 1] and maintaining aspect ratio.
3. Output 3d keypoints are in H3.6m format (https://github.com/facebookresearch/VideoPose3D/issues/36), i.e. same as Videopose3d output.

Still, I end up with randomly located keypoints. Anything I might be missing??

Also, @AO2233 I'd be grateful if you can please share the email contents (that you shared with @Whisht ) here.

**Comment by TomCatOnline** [comment]
> 

@safsin Have you recieved their email? It would be kind if you could tell me how you did your preprocessing step 1、2、3, please.
Looking forward to your reply, thank you very much!

**Comment by safsin** [comment]
@TomCatOnline I haven't received any emails yet. These are the preprocessing steps I followed (which doesn't seem to work for me) in detail - 
1. The input 2d keypoints should be in H3.6m format, unlike the COCO format most 2d human pose detectors' output in.
2. Normalize the input 2d keypoints in the range [-1, 1].

You can also try using https://github.com/paTRICK-swk/P-STMO. It has much better examples and codes for in-the-wild human pose3d detection. Better look into it.

**Comment by TomCatOnline** [comment]
> @TomCatOnline I haven't received any emails yet. These are the preprocessing steps I followed (which doesn't seem to work for me) in detail -
> 
> 1. The input 2d keypoints should be in H3.6m format, unlike the COCO format most 2d human pose detectors' output in.
> 2. Normalize the input 2d keypoints in the range [-1, 1].
> 
> You can also try using https://github.com/paTRICK-swk/P-STMO. It has much better examples and codes for in-the-wild human pose3d detection. Better look into it.

I was traped by detectron2 output coco format 2d keypoints but don't know how to convert to h36m format, will look into [it](https://github.com/paTRICK-swk/P-STMO), thanks for your quick reply!

**Comment by Deleter-D** [comment]
> @FinallyKiKi @ClimberXIE This Net input format is human3.6M's 17 points You need to change the COCO format 17 points from the detectron2 of VideoPose3d to human3.6M's 17 points As for the code, click here for reference: https://github.com/fabro66/GAST-Net-3DPoseEstimation/blob/master/tools/mpii_coco_h36m.py and then
> 
> ```python
> # first load your videopose 2d coco points
> loaded = np.load('PoseFormer/data/data_2d_custom_myvideos.npz', allow_pickle=True)
> data = loaded['positions_2d'].item()
> for i in data:
>     # convert them to human3.6M format
>     data[i]['custom'][0]=coco_h36m(data[i]['custom'][0])
> np.savez_compressed('data_2d_custom_myvideos', positions_2d=data, metadata=loaded['metadata'])
> ```

Thanks for your help on this. I did so, and the `data_2d_custom_myvideo.npz` file became like this.
<img width=“654” alt="image" src="https://user-images.githubusercontent.com/56388518/222338429-73d56aec-6276-4052-bc43-cb9aa508a460.png">
The first half is the joint point coordinates, and there is an array at the end that records the total number of frames of my wild video. Is this format correct?

After this, a new problem arose.
There is the information: 
```
Traceback （most recent call last）:
  File "run_poseformer.py", line 112, in <module>
    kps[..., :2] = normalize_screen_coordinates(kps[..., :2], w=cam['res_w'], h=cam['res_h'])
TypeError: tuple indices must be integers or slices, not tuple
```
Do you know what the problem is? Thanks again for help.
